name: instagram
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

fonts:
  - family: GR
    fonts:
      - asset: fonts/GilroyRegular.ttf
        weight: 400

  - family: GM
    fonts:
      - asset: fonts/GilroyMedium.ttf
        weight: 500

  - family: GB
    fonts:
      - asset: fonts/GilroyBold.ttf
        weight: 700

  - family: GEB
    fonts:
      - asset: fonts/GilroyExtraBold.ttf
        weight: 800

  - family: GH
    fonts:
      - asset: fonts/GilroyHeavy.ttf
        weight: 900
